plugins:
  discourse_github_verification_enabled:
    default: true
    client: true
  discourse_github_verification_client_id:
    default: ""
    client: true
  discourse_github_verification_client_secret:
    default: ""
